---
  metamask:
    language: 'en'

  game:
    amount_of_spaceships: 15

  logger:
    enable: True
    path: 'logs'

  telegram:
    enable: False
    level: 'error' # error, warning, info
    token_api: 'your_bot_token'
    chat_id: 'your_chat_id'
  
  others:
    drag_amount_mouse: 200
  
  detector:
    images_path: 'images'
  # time_intervals:
  #   send_heroes_for_work: 10
  #   refresh_heroes_positions: 3
  #   check_for_new_map_button: 5
  #   check_for_captcha: 1
  #   check_for_login: 5
  #   interval_between_moviments: 1
  # threshold:
  #   default: 0.7
  #   commom: 0.8
  #   select_wallet_buttons: 0.8
  #   go_to_work_btn: 0.9
  #   green_bar: 0.9

  # home:
  #   enable: False
  #   hero_threshold: 0.8
  #   home_button_threshold: 0.9

  # scroll_size: 60
  # scroll_attemps: 3
  # use_click_and_drag_instead_of_scroll: true
  # click_and_drag_amount: 200
  # save_log_to_file: True
  # telegram:
  #   level: 'disable'
  #   token_api: 'your_bot_token'
  #   chat_id: 'your_chat_id'
---